// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nanopb.proto

package fi.kapsi.koti.jpa.nanopb;

public final class Nanopb {
  private Nanopb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(fi.kapsi.koti.jpa.nanopb.Nanopb.nanopbFileopt);
    registry.add(fi.kapsi.koti.jpa.nanopb.Nanopb.nanopbMsgopt);
    registry.add(fi.kapsi.koti.jpa.nanopb.Nanopb.nanopbEnumopt);
    registry.add(fi.kapsi.koti.jpa.nanopb.Nanopb.nanopb);
  }
  /**
   * Protobuf enum {@code FieldType}
   */
  public enum FieldType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FT_DEFAULT = 0;</code>
     *
     * <pre>
     * Automatically decide field type, generate static field if possible.
     * </pre>
     */
    FT_DEFAULT(0, 0),
    /**
     * <code>FT_CALLBACK = 1;</code>
     *
     * <pre>
     * Always generate a callback field.
     * </pre>
     */
    FT_CALLBACK(1, 1),
    /**
     * <code>FT_STATIC = 2;</code>
     *
     * <pre>
     * Generate a static field or raise an exception if not possible.
     * </pre>
     */
    FT_STATIC(2, 2),
    /**
     * <code>FT_IGNORE = 3;</code>
     *
     * <pre>
     * Ignore the field completely.
     * </pre>
     */
    FT_IGNORE(3, 3),
    ;

    /**
     * <code>FT_DEFAULT = 0;</code>
     *
     * <pre>
     * Automatically decide field type, generate static field if possible.
     * </pre>
     */
    public static final int FT_DEFAULT_VALUE = 0;
    /**
     * <code>FT_CALLBACK = 1;</code>
     *
     * <pre>
     * Always generate a callback field.
     * </pre>
     */
    public static final int FT_CALLBACK_VALUE = 1;
    /**
     * <code>FT_STATIC = 2;</code>
     *
     * <pre>
     * Generate a static field or raise an exception if not possible.
     * </pre>
     */
    public static final int FT_STATIC_VALUE = 2;
    /**
     * <code>FT_IGNORE = 3;</code>
     *
     * <pre>
     * Ignore the field completely.
     * </pre>
     */
    public static final int FT_IGNORE_VALUE = 3;


    public final int getNumber() { return value; }

    public static FieldType valueOf(int value) {
      switch (value) {
        case 0: return FT_DEFAULT;
        case 1: return FT_CALLBACK;
        case 2: return FT_STATIC;
        case 3: return FT_IGNORE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FieldType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<FieldType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FieldType>() {
            public FieldType findValueByNumber(int number) {
              return FieldType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return fi.kapsi.koti.jpa.nanopb.Nanopb.getDescriptor().getEnumTypes().get(0);
    }

    private static final FieldType[] VALUES = values();

    public static FieldType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private FieldType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:FieldType)
  }

  public interface NanoPBOptionsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 max_size = 1;
    /**
     * <code>optional int32 max_size = 1;</code>
     *
     * <pre>
     * Allocated size for 'bytes' and 'string' fields.
     * </pre>
     */
    boolean hasMaxSize();
    /**
     * <code>optional int32 max_size = 1;</code>
     *
     * <pre>
     * Allocated size for 'bytes' and 'string' fields.
     * </pre>
     */
    int getMaxSize();

    // optional int32 max_count = 2;
    /**
     * <code>optional int32 max_count = 2;</code>
     *
     * <pre>
     * Allocated number of entries in arrays ('repeated' fields)
     * </pre>
     */
    boolean hasMaxCount();
    /**
     * <code>optional int32 max_count = 2;</code>
     *
     * <pre>
     * Allocated number of entries in arrays ('repeated' fields)
     * </pre>
     */
    int getMaxCount();

    // optional .FieldType type = 3 [default = FT_DEFAULT];
    /**
     * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
     *
     * <pre>
     * Force type of field (callback or static allocation)
     * </pre>
     */
    boolean hasType();
    /**
     * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
     *
     * <pre>
     * Force type of field (callback or static allocation)
     * </pre>
     */
    fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType getType();

    // optional bool long_names = 4 [default = true];
    /**
     * <code>optional bool long_names = 4 [default = true];</code>
     *
     * <pre>
     * Use long names for enums, i.e. EnumName_EnumValue.
     * </pre>
     */
    boolean hasLongNames();
    /**
     * <code>optional bool long_names = 4 [default = true];</code>
     *
     * <pre>
     * Use long names for enums, i.e. EnumName_EnumValue.
     * </pre>
     */
    boolean getLongNames();

    // optional bool packed_struct = 5 [default = false];
    /**
     * <code>optional bool packed_struct = 5 [default = false];</code>
     *
     * <pre>
     * Add 'packed' attribute to generated structs.
     * </pre>
     */
    boolean hasPackedStruct();
    /**
     * <code>optional bool packed_struct = 5 [default = false];</code>
     *
     * <pre>
     * Add 'packed' attribute to generated structs.
     * </pre>
     */
    boolean getPackedStruct();
  }
  /**
   * Protobuf type {@code NanoPBOptions}
   */
  public static final class NanoPBOptions extends
      com.google.protobuf.GeneratedMessage
      implements NanoPBOptionsOrBuilder {
    // Use NanoPBOptions.newBuilder() to construct.
    private NanoPBOptions(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NanoPBOptions(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NanoPBOptions defaultInstance;
    public static NanoPBOptions getDefaultInstance() {
      return defaultInstance;
    }

    public NanoPBOptions getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NanoPBOptions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              maxSize_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              maxCount_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType value = fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                type_ = value;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              longNames_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              packedStruct_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fi.kapsi.koti.jpa.nanopb.Nanopb.internal_static_NanoPBOptions_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fi.kapsi.koti.jpa.nanopb.Nanopb.internal_static_NanoPBOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.class, fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.Builder.class);
    }

    public static com.google.protobuf.Parser<NanoPBOptions> PARSER =
        new com.google.protobuf.AbstractParser<NanoPBOptions>() {
      public NanoPBOptions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NanoPBOptions(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NanoPBOptions> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 max_size = 1;
    public static final int MAX_SIZE_FIELD_NUMBER = 1;
    private int maxSize_;
    /**
     * <code>optional int32 max_size = 1;</code>
     *
     * <pre>
     * Allocated size for 'bytes' and 'string' fields.
     * </pre>
     */
    public boolean hasMaxSize() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 max_size = 1;</code>
     *
     * <pre>
     * Allocated size for 'bytes' and 'string' fields.
     * </pre>
     */
    public int getMaxSize() {
      return maxSize_;
    }

    // optional int32 max_count = 2;
    public static final int MAX_COUNT_FIELD_NUMBER = 2;
    private int maxCount_;
    /**
     * <code>optional int32 max_count = 2;</code>
     *
     * <pre>
     * Allocated number of entries in arrays ('repeated' fields)
     * </pre>
     */
    public boolean hasMaxCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 max_count = 2;</code>
     *
     * <pre>
     * Allocated number of entries in arrays ('repeated' fields)
     * </pre>
     */
    public int getMaxCount() {
      return maxCount_;
    }

    // optional .FieldType type = 3 [default = FT_DEFAULT];
    public static final int TYPE_FIELD_NUMBER = 3;
    private fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType type_;
    /**
     * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
     *
     * <pre>
     * Force type of field (callback or static allocation)
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
     *
     * <pre>
     * Force type of field (callback or static allocation)
     * </pre>
     */
    public fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType getType() {
      return type_;
    }

    // optional bool long_names = 4 [default = true];
    public static final int LONG_NAMES_FIELD_NUMBER = 4;
    private boolean longNames_;
    /**
     * <code>optional bool long_names = 4 [default = true];</code>
     *
     * <pre>
     * Use long names for enums, i.e. EnumName_EnumValue.
     * </pre>
     */
    public boolean hasLongNames() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool long_names = 4 [default = true];</code>
     *
     * <pre>
     * Use long names for enums, i.e. EnumName_EnumValue.
     * </pre>
     */
    public boolean getLongNames() {
      return longNames_;
    }

    // optional bool packed_struct = 5 [default = false];
    public static final int PACKED_STRUCT_FIELD_NUMBER = 5;
    private boolean packedStruct_;
    /**
     * <code>optional bool packed_struct = 5 [default = false];</code>
     *
     * <pre>
     * Add 'packed' attribute to generated structs.
     * </pre>
     */
    public boolean hasPackedStruct() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool packed_struct = 5 [default = false];</code>
     *
     * <pre>
     * Add 'packed' attribute to generated structs.
     * </pre>
     */
    public boolean getPackedStruct() {
      return packedStruct_;
    }

    private void initFields() {
      maxSize_ = 0;
      maxCount_ = 0;
      type_ = fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType.FT_DEFAULT;
      longNames_ = true;
      packedStruct_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, maxSize_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, maxCount_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, longNames_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, packedStruct_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, maxSize_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, maxCount_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, longNames_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, packedStruct_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NanoPBOptions}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fi.kapsi.koti.jpa.nanopb.Nanopb.internal_static_NanoPBOptions_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fi.kapsi.koti.jpa.nanopb.Nanopb.internal_static_NanoPBOptions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.class, fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.Builder.class);
      }

      // Construct using fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        maxSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        maxCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType.FT_DEFAULT;
        bitField0_ = (bitField0_ & ~0x00000004);
        longNames_ = true;
        bitField0_ = (bitField0_ & ~0x00000008);
        packedStruct_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fi.kapsi.koti.jpa.nanopb.Nanopb.internal_static_NanoPBOptions_descriptor;
      }

      public fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions getDefaultInstanceForType() {
        return fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.getDefaultInstance();
      }

      public fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions build() {
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions buildPartial() {
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions result = new fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.maxSize_ = maxSize_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.maxCount_ = maxCount_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.longNames_ = longNames_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.packedStruct_ = packedStruct_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions) {
          return mergeFrom((fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions other) {
        if (other == fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.getDefaultInstance()) return this;
        if (other.hasMaxSize()) {
          setMaxSize(other.getMaxSize());
        }
        if (other.hasMaxCount()) {
          setMaxCount(other.getMaxCount());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasLongNames()) {
          setLongNames(other.getLongNames());
        }
        if (other.hasPackedStruct()) {
          setPackedStruct(other.getPackedStruct());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 max_size = 1;
      private int maxSize_ ;
      /**
       * <code>optional int32 max_size = 1;</code>
       *
       * <pre>
       * Allocated size for 'bytes' and 'string' fields.
       * </pre>
       */
      public boolean hasMaxSize() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 max_size = 1;</code>
       *
       * <pre>
       * Allocated size for 'bytes' and 'string' fields.
       * </pre>
       */
      public int getMaxSize() {
        return maxSize_;
      }
      /**
       * <code>optional int32 max_size = 1;</code>
       *
       * <pre>
       * Allocated size for 'bytes' and 'string' fields.
       * </pre>
       */
      public Builder setMaxSize(int value) {
        bitField0_ |= 0x00000001;
        maxSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 max_size = 1;</code>
       *
       * <pre>
       * Allocated size for 'bytes' and 'string' fields.
       * </pre>
       */
      public Builder clearMaxSize() {
        bitField0_ = (bitField0_ & ~0x00000001);
        maxSize_ = 0;
        onChanged();
        return this;
      }

      // optional int32 max_count = 2;
      private int maxCount_ ;
      /**
       * <code>optional int32 max_count = 2;</code>
       *
       * <pre>
       * Allocated number of entries in arrays ('repeated' fields)
       * </pre>
       */
      public boolean hasMaxCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 max_count = 2;</code>
       *
       * <pre>
       * Allocated number of entries in arrays ('repeated' fields)
       * </pre>
       */
      public int getMaxCount() {
        return maxCount_;
      }
      /**
       * <code>optional int32 max_count = 2;</code>
       *
       * <pre>
       * Allocated number of entries in arrays ('repeated' fields)
       * </pre>
       */
      public Builder setMaxCount(int value) {
        bitField0_ |= 0x00000002;
        maxCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 max_count = 2;</code>
       *
       * <pre>
       * Allocated number of entries in arrays ('repeated' fields)
       * </pre>
       */
      public Builder clearMaxCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        maxCount_ = 0;
        onChanged();
        return this;
      }

      // optional .FieldType type = 3 [default = FT_DEFAULT];
      private fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType type_ = fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType.FT_DEFAULT;
      /**
       * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
       *
       * <pre>
       * Force type of field (callback or static allocation)
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
       *
       * <pre>
       * Force type of field (callback or static allocation)
       * </pre>
       */
      public fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType getType() {
        return type_;
      }
      /**
       * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
       *
       * <pre>
       * Force type of field (callback or static allocation)
       * </pre>
       */
      public Builder setType(fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
       *
       * <pre>
       * Force type of field (callback or static allocation)
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType.FT_DEFAULT;
        onChanged();
        return this;
      }

      // optional bool long_names = 4 [default = true];
      private boolean longNames_ = true;
      /**
       * <code>optional bool long_names = 4 [default = true];</code>
       *
       * <pre>
       * Use long names for enums, i.e. EnumName_EnumValue.
       * </pre>
       */
      public boolean hasLongNames() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool long_names = 4 [default = true];</code>
       *
       * <pre>
       * Use long names for enums, i.e. EnumName_EnumValue.
       * </pre>
       */
      public boolean getLongNames() {
        return longNames_;
      }
      /**
       * <code>optional bool long_names = 4 [default = true];</code>
       *
       * <pre>
       * Use long names for enums, i.e. EnumName_EnumValue.
       * </pre>
       */
      public Builder setLongNames(boolean value) {
        bitField0_ |= 0x00000008;
        longNames_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool long_names = 4 [default = true];</code>
       *
       * <pre>
       * Use long names for enums, i.e. EnumName_EnumValue.
       * </pre>
       */
      public Builder clearLongNames() {
        bitField0_ = (bitField0_ & ~0x00000008);
        longNames_ = true;
        onChanged();
        return this;
      }

      // optional bool packed_struct = 5 [default = false];
      private boolean packedStruct_ ;
      /**
       * <code>optional bool packed_struct = 5 [default = false];</code>
       *
       * <pre>
       * Add 'packed' attribute to generated structs.
       * </pre>
       */
      public boolean hasPackedStruct() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool packed_struct = 5 [default = false];</code>
       *
       * <pre>
       * Add 'packed' attribute to generated structs.
       * </pre>
       */
      public boolean getPackedStruct() {
        return packedStruct_;
      }
      /**
       * <code>optional bool packed_struct = 5 [default = false];</code>
       *
       * <pre>
       * Add 'packed' attribute to generated structs.
       * </pre>
       */
      public Builder setPackedStruct(boolean value) {
        bitField0_ |= 0x00000010;
        packedStruct_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool packed_struct = 5 [default = false];</code>
       *
       * <pre>
       * Add 'packed' attribute to generated structs.
       * </pre>
       */
      public Builder clearPackedStruct() {
        bitField0_ = (bitField0_ & ~0x00000010);
        packedStruct_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NanoPBOptions)
    }

    static {
      defaultInstance = new NanoPBOptions(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NanoPBOptions)
  }

  public static final int NANOPB_FILEOPT_FIELD_NUMBER = 1010;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions> nanopbFileopt = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.class,
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.getDefaultInstance());
  public static final int NANOPB_MSGOPT_FIELD_NUMBER = 1010;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions> nanopbMsgopt = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.class,
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.getDefaultInstance());
  public static final int NANOPB_ENUMOPT_FIELD_NUMBER = 1010;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions> nanopbEnumopt = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.class,
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.getDefaultInstance());
  public static final int NANOPB_FIELD_NUMBER = 1010;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions> nanopb = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.class,
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.getDefaultInstance());
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NanoPBOptions_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NanoPBOptions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014nanopb.proto\032 google/protobuf/descript" +
      "or.proto\"\222\001\n\rNanoPBOptions\022\020\n\010max_size\030\001" +
      " \001(\005\022\021\n\tmax_count\030\002 \001(\005\022$\n\004type\030\003 \001(\0162\n." +
      "FieldType:\nFT_DEFAULT\022\030\n\nlong_names\030\004 \001(" +
      "\010:\004true\022\034\n\rpacked_struct\030\005 \001(\010:\005false*J\n" +
      "\tFieldType\022\016\n\nFT_DEFAULT\020\000\022\017\n\013FT_CALLBAC" +
      "K\020\001\022\r\n\tFT_STATIC\020\002\022\r\n\tFT_IGNORE\020\003:E\n\016nan" +
      "opb_fileopt\022\034.google.protobuf.FileOption" +
      "s\030\362\007 \001(\0132\016.NanoPBOptions:G\n\rnanopb_msgop" +
      "t\022\037.google.protobuf.MessageOptions\030\362\007 \001(",
      "\0132\016.NanoPBOptions:E\n\016nanopb_enumopt\022\034.go" +
      "ogle.protobuf.EnumOptions\030\362\007 \001(\0132\016.NanoP" +
      "BOptions:>\n\006nanopb\022\035.google.protobuf.Fie" +
      "ldOptions\030\362\007 \001(\0132\016.NanoPBOptionsB\032\n\030fi.k" +
      "apsi.koti.jpa.nanopb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_NanoPBOptions_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_NanoPBOptions_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NanoPBOptions_descriptor,
              new java.lang.String[] { "MaxSize", "MaxCount", "Type", "LongNames", "PackedStruct", });
          nanopbFileopt.internalInit(descriptor.getExtensions().get(0));
          nanopbMsgopt.internalInit(descriptor.getExtensions().get(1));
          nanopbEnumopt.internalInit(descriptor.getExtensions().get(2));
          nanopb.internalInit(descriptor.getExtensions().get(3));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
